---
title: Neurocomputing
subtitle: Foreword

author: Julien Vitay
institute: Professur für Künstliche Intelligenz - Fakultät für Informatik

---

# Dr. habil. Julien Vitay

<https://julien-vitay.net>

<julien.vitay@informatik.tu-chemnitz.de>

::: {.columns}
::: {.column}

**Background**

* 2002: Master in Electrical Engineering (Supélec).

* 2006: Ph.D in Computer Science (Inria).

    * Emergence of sensorimotor function on a distributed numerical substrate.

* Postdoc in Psychology (Münster).

* 2011: lecturer at TU Chemnitz:

    * Habilitation in 2017:

        * On the role of dopamine in motivated behavior: a neuro-computational approach.

    * Courses: machine learning, computer vision, deep RL.

:::
::: {.column}

**Research**

* Computational neuroscience

    * Dopamine, biological reinforcement learning

    * Basal Ganglia, decision-making

    * Cerebellum, motor control

    * Hippocampus, memory

* Machine learning

    * Reservoir computing

    * Successor representations

    * Graph neural networks

    * Deep reinforcement learning

:::
:::

* Erasmus coordinator:  <https://www.tu-chemnitz.de/informatik/international/erasmus.php.en>

# Course description

* **Neurocomputing** (573180) replaces the previous Machine Learning (573050) course.

* If you have ML in your study regulations, you **can** take Neurocomputing instead.

* Reinforcement Learning is now in the **Deep Reinforcement Learning** (573140) course.

    * Master Neurorobotik.

    * Master Data Science.

    * Master Informatik (Multi-Agent systems) and angewandte Informatik (Themenschwerpunkte Informatik I/II).


* Other ML-related courses at the University:

    * Introduction to AI I (Inf, Prof. Hamker) and II (Inf, Prof. Röhrbein)

    * Introduction to Data Science (Mathe, Prof. Ernst)

    * Image Processing and Pattern Recognition (ETIT, Prof. Mößner)



# Course description

* Registration and forum on OPAL: 

<https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/21637267460>.

* One lecture (Tuesday 17:15) and one exercise per week:

    * Tuesday 13:45
    * Wednesday 07:30
    * Friday 09:30

* Register on OPAL in one of the three exercise groups. Exercises can also be done online.

* All materials are at:

<https://www.tu-chemnitz.de/informatik/KI/edu/neurocomputing/notes>

* The videos might be slightly outdated, but still cover most of the important content.

* Written exam, 90 minutes, 5 credit points.



# Exercises

* Exercises : programming in Python the algorithms seen in the course (using tensorflow, keras, scikit-learn).

* The first exercises are a tutorial on Python and Numpy (common with DRL and CV).

* Exercises are there to better understand the algorithms and learn to use the modern tools.

* There will be no programming question at the exam, but some may be related to the exercises.

